spring:
  application:
    name: api-rest-users
  profiles:
    include:
      - dev
  datasource:
    url: jdbc:h2:mem:nisum-challenge
    username: us
    password: ${DB_PASS:123456}
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring.jpa.hibernate.ddl-auto: update
  h2:
    console.path: /h2-console
    console.settings.trace: false
    console.enabled: true
    spring.h2.console.settings.web-allow-others: false
  flyway:
    enabled: true
    locations: classpath:/db/migration
    validate-on-migrate: true
server:
  port: ${PORT:8080}
  servlet:
    contextPath: /api
  error:
    include-stacktrace: never
    path: never
